version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Restore Packages
          command:
            dotnet restore
      - run:
          name: Build Projects
          command:
            dotnet build
      - run:
          name: Tests
          command:
            dotnet test tests/dotenv.net.Tests/dotenv.net.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - run:
          name: Install Coveralls
          command:
            dotnet tool install coveralls.net --version 3.0.0 --tool-path tools
      - run:
          name: Report Coverage
          command:
            ./tools/csmacnz.Coveralls --opencover -i ./results/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $CIRCLE_SHA1 --commitBranch $CIRCLE_BRANCH --commitAuthor "$CIRCLE_USERNAME" --jobId $CIRCLE_BUILD_NUM --serviceName "circleci" --useRelativePaths
