version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build the project
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Run tests and generate coverage report
          command: |
            dotnet test --configuration Release --no-build --logger trx --results-directory TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/coverage.cobertura.xml
      - run:
          name: Install coveralls.net
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global coveralls.net
      - run:
          name: Report coverage to Coveralls
          command: coveralls.net --repoToken $COVERALLS_REPO_TOKEN --input TestResults/coverage.cobertura.xml --commitId $CIRCLE_SHA1 --commitBranch $CIRCLE_BRANCH --commitAuthor "$CIRCLE_USERNAME" --jobId $CIRCLE_BUILD_NUM --serviceName "circleci" --useRelativePaths
