name: CI - Build, Test & Coverage

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build all projects
        run: dotnet build --no-restore

      - name: Run tests with code coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ${{ github.workspace }}/src/dotenv.net.Tests/coverage/coverage.info
